vich_uploader:
    db_driver: orm

    mappings:
        picture_path:
            uri_prefix: /assets/images/
            upload_destination: '%kernel.project_dir%/public/assets/images'
            inject_on_load: false
            delete_on_update: true
            delete_on_remove: true
            namer: Vich\UploaderBundle\Naming\UniqidNamer
